---
- name: Testing andrewrothstein.tea
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'tea --version'
      ansible.builtin.command: tea --version
      changed_when: false
      register: tea_test_output
    - name: Output of 'tea --version'
      ansible.builtin.debug:
        msg: '{{ tea_test_output.stdout }}'
